name: app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  device_preview: ^1.1.0
  google_fonts: ^6.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash-screen.png
    - assets/line-header.png
    - assets/five.png
    - assets/ten.png
    - assets/twenty-five.png
    - assets/fifty.png
    - assets/one-hundred.png
    - assets/two-hundred.png
    - assets/home-screen.png
    - assets/home-screen-wood.png
    - assets/home-screen-black.png
    - assets/home-five.png
    - assets/home-ten.png
    - assets/home-twenty-five.png
    - assets/home-fifty.png
    - assets/home-one-hundred.png
    - assets/home-two-hundred.png
    - assets/home-money.png
    - assets/home-settings.png
    - assets/home-invite.png
    - assets/home-deck.png
    - assets/home-deck-aux.png
    - assets/clear-up.png
    - assets/clear-down.png
    - assets/deal-up.png
    - assets/deal-down.png
    - assets/double-up.png
    - assets/double-down.png
    - assets/hit-up.png
    - assets/hit-down.png
    - assets/split-up.png
    - assets/split-down.png
    - assets/stand-up.png
    - assets/stand-down.png
    - assets/score.png
